services:
  frontend:
    container_name: frontend
    build:
      context: frontend
    volumes:
      - ./frontend:/home/node/app
    depends_on:
      - backend
    ports:
      - 5173:5173

  backend:
    container_name: backend
    build: 
      context: backend
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
